//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codelife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int commentId { get; set; }
        public string comment1 { get; set; }
        public string commentator { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public Nullable<int> authorId { get; set; }
        public Nullable<int> postId { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Post Post { get; set; }
    }
}
